export ZSH="/home/marioallves/.oh-my-zsh"
ZSH_THEME="hirakata"
plugins=(hirakata )

# User configuration

export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
source $ZSH/oh-my-zsh.sh
source ~/.config/zsh/aliases
