#!/bin/bash
## Shortcut to search, add, and play an album (after clearing current playlist).
## Use -a (for "add") to add the album to the playlist without clearing current playlist.
 
if [ $1 = -a ]
then
shift
mpc search artist "$*" | mpc add ; mpc play
exit
fi
 
mpc clear
mpc search artist "$*" | mpc add ; mpc play